### ISSUE TITLE
failed to check archive integrity of the plugin 

### ISSUE THREAD

**Issue by flippinjoe** [traefik-plugins/traefikgeoip2#1]
After following the readme instructions, I'm receiving an integrity check error on v0.1.0.  According to https://github.com/traefik/traefik/issues/7704 if tags are reused this could cause the problem.  Wondering if that's the case here?  If so, can you create a new release please 😀

**Comment by rossnick** [comment]
I had that plugin worked for me for a while with version 0.1.0, and now it fails to load for the same reason.

**Comment by rossnick** [comment]
@flippinjoe I saw you forked the plugin. Have you been able to make it work with your repo ?
I get :
error: 404: {\"error\":\"Unknown plugin: github.com/flippinjoe/traefikgeoip2@v0.1.1\"}

**Comment by ievgenii-shepeliuk** [comment]
Hello

`v0.20.1` is available and for me is installed OK. Please give it a try.

**Comment by rossnick** [comment]
Thanks, it works
