### ISSUE TITLE
Docker example

### ISSUE THREAD

**Issue by kpatronas** [traefik-plugins/traefikgeoip2#3]
Hello

I was wondering how we can use this with plain docker, can you please create an example? can this project considered functional of production environments?

BR

**Comment by ievgenii-shepeliuk** [comment]
Hello

> I was wondering how we can use this with plain docker, can you please create an example? 

The only specific thing is that you need to mount GeoIP database into Traefik container with regular `-v` option. Then enable and configure it for you routes [as any other plugin](https://plugins.traefik.io/install).

> can this project considered functional of production environments?

Yes it is, about 2 yrs in active usage.

**Comment by carsti-nator** [comment]
Hello all/@ievgenii-shepeliuk 

sorry for posting in this old thread, but I basically have the same request as initally raised from kpatronas: an example on how to activate the plugin.

I was able to install the plugin (for docker) and prepare the middleware.
My main question however is: How do I whitelist / blacklist certain countries when using the middleware? I am probably just missing a very small step...

(filetype toml)
```
[http.middlewares.geoip2.plugin.geoip]
  dbPath = "/geoip2/GeoLite2-City.mmdb"

# Testing with the traefik Dashboard/API
[http.routers.api]
  rule = "Host(`test.domain.com`)"
  entrypoints = ["websecure"]
  middlewares = ["geoip2"]
  service = "api@internal"
  [http.routers.test.tls]
    certResolver = "my-resolver"`
``` 

Many thanks in advance.

**Comment by eshepelyuk** [comment]
Hello

This plugin doesn't perform any whitelisting or blacklisting. It only populates request headers with GeoIP information.

**Comment by carsti-nator** [comment]
Ahh okey. Thanks :-)
