### ISSUE TITLE
How to update the DB without restart the Traefik service?

### ISSUE THREAD

**Issue by ttt-ccc** [traefik-plugins/traefikgeoip2#7]
I want to update the GeoIpDB , but after I change the new DB path in dynamic_conf.yml,but it seems doesn't work.
Before:
```my-traefikgeoip2:
      plugin:
        traefikgeoip2:
          dbPath: /etc/traefik/GeoLite2-Country.mmdb
```
After:
```my-traefikgeoip2:
      plugin:
        traefikgeoip2:
          dbPath: /etc/traefik/GeoLite2-Country-0611.mmdb
```
Do I have to restart traefik to take effect?

**Comment by eshepelyuk** [comment]
Hello

1. What is `dynamic_conf.yml` ?
2. How do you deploy `traefik` : docker, k8s, standalone ?

**Comment by ttt-ccc** [comment]
Thank you for your reply 
1.the dynamic_conf.yml  is a dynamic configuration file, in order to monitor configuration changes without restarting treafik, You could refer to this : https://doc.traefik.io/traefik/providers/file/#watch or https://doc.traefik.io/traefik/reference/dynamic-configuration/file/ , 
2.In Docker Swarm mode

**Comment by eshepelyuk** [comment]
> Thank you for your reply 1.the dynamic_conf.yml is a dynamic configuration file, in order to monitor configuration changes without restarting treafik, You could refer to this : https://doc.traefik.io/traefik/providers/file/#watch or https://doc.traefik.io/traefik/reference/dynamic-configuration/file/ , 2.In Docker Swarm mode

Ok, I worked only with K8s, so in K8s as soon as Middleware CRD changed - the plugins and other configuration is reloaded / restarted by Traefik itself.

Unfortunately, have no idea how it behaves in Docker Swarm, so my suggestion will be to restart Traefik.
Since plugin itself can not enforce such behaviour.
